use std::path::Path;

use anyhow::Context;

/// Fase 10 (SPEC.md §12): opt-in log forwarding, default off. Off means today's exact behavior —
/// `access_log`/`error_log` writing to the files the base Nginx image already symlinks to
/// `/dev/stdout`/`/dev/stderr`, so `docker logs` keeps working per replica with zero change. On
/// uses Nginx's own native `syslog:` sink — no local rsyslog daemon, the agent keeps supervising
/// exactly one child process (Nginx), matching the existing invariant.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LogDestination {
    Local,
    Syslog { host: String, port: u16 },
}

/// Pure (no direct env access) so it's unit-testable without env vars — same pattern as
/// `config::resolve_replica_hostname_from`.
pub fn resolve_log_destination(
    enabled: bool,
    host: Option<String>,
    port: u16,
) -> anyhow::Result<LogDestination> {
    if !enabled {
        return Ok(LogDestination::Local);
    }

    let host = host.ok_or_else(|| {
        anyhow::anyhow!("CENTRAL_LOG_SERVER_HOST is required when LOG_FORWARDING_ENABLED=true")
    })?;

    Ok(LogDestination::Syslog { host, port })
}

/// The file this renders (`logging.conf`) is **not** a repo file baked into the image at build
/// time like the sibling static snippets (`ssl-common.conf`/`security-headers.conf`/
/// `websocket.conf`/`acme-challenge.conf`) — it only exists once the agent writes it here, at
/// boot, based on runtime config. `nginx/nginx.conf`'s `include` line has a comment pointing back
/// at this distinction.
pub fn render_snippet(destination: &LogDestination) -> String {
    let directives = match destination {
        LogDestination::Local => {
            "error_log /var/log/nginx/error.log notice;\naccess_log /var/log/nginx/access.log main;".to_string()
        }
        LogDestination::Syslog { host, port } => format!(
            "error_log syslog:server={host}:{port},tag=apy_gateway_nginx,severity=notice;\n\
             access_log syslog:server={host}:{port},tag=apy_gateway_nginx main;"
        ),
    };

    format!("# Generated by apy-agent at boot — do not hand-edit, changes are lost on restart.\n{directives}\n")
}

pub fn write_snippet(snippets_dir: &Path, destination: &LogDestination) -> anyhow::Result<()> {
    std::fs::create_dir_all(snippets_dir)
        .with_context(|| format!("creating {}", snippets_dir.display()))?;

    let target = snippets_dir.join("logging.conf");
    std::fs::write(&target, render_snippet(destination))
        .with_context(|| format!("writing {}", target.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_to_local_when_disabled_even_with_host_set() {
        let dest = resolve_log_destination(false, Some("log-server".to_string()), 514).unwrap();
        assert_eq!(dest, LogDestination::Local);
    }

    #[test]
    fn resolves_to_syslog_when_enabled_with_host() {
        let dest = resolve_log_destination(true, Some("log-server".to_string()), 514).unwrap();
        assert_eq!(dest, LogDestination::Syslog { host: "log-server".to_string(), port: 514 });
    }

    #[test]
    fn errors_when_enabled_without_host() {
        assert!(resolve_log_destination(true, None, 514).is_err());
    }

    #[test]
    fn renders_local_snippet_matching_the_previous_static_directives() {
        let rendered = render_snippet(&LogDestination::Local);
        assert!(rendered.contains("error_log /var/log/nginx/error.log notice;"));
        assert!(rendered.contains("access_log /var/log/nginx/access.log main;"));
        assert!(!rendered.contains("syslog"));
    }

    #[test]
    fn renders_syslog_snippet_with_configured_target() {
        let rendered = render_snippet(&LogDestination::Syslog { host: "log-server".to_string(), port: 514 });
        assert!(rendered.contains("error_log syslog:server=log-server:514,tag=apy_gateway_nginx,severity=notice;"));
        assert!(rendered.contains("access_log syslog:server=log-server:514,tag=apy_gateway_nginx main;"));
    }

    #[test]
    fn write_snippet_creates_the_directory_and_file() {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("apy-agent-test-logging-config-{nanos}"));

        write_snippet(&dir, &LogDestination::Local).unwrap();

        let content = std::fs::read_to_string(dir.join("logging.conf")).unwrap();
        assert!(content.contains("access_log /var/log/nginx/access.log main;"));
    }
}
